### ISSUE TITLE
How to run it ?

### ISSUE THREAD

**Issue by Houston4444** [SanderVocke/shoopdaloop#235]
Hi.
I am curious with this program, I would like to test it, but I don't understand the way to do.
I installed all the dependencies (I run Debian Bullseye), downloaded a wheel in your Github actions page, installed it running my python virtual env, and then, how to start it ?
I tried to launch 
```python3 src/shoopdaloop```

mmmh, it starts, yes, but, it's a big animation where user can't interact, there is probably a script testing the software.

I think you should also explain in install.sh, how to download a wheel (there are many, many items in github actions page), and quickly how to install and run a python env.

**Comment by SanderVocke** [comment]
Since you may not be the last to ask this, I made an announcement on the discussion board: 
https://github.com/SanderVocke/shoopdaloop/discussions/238

So I will close this issue, feel free to re-open if anything is unclear.

**Comment by zigmhount** [comment]
Hi @SanderVocke,

Thanks for your work on this, it looks very exciting! Like @Houston4444 , I'd love to give it a try (especially after seeing your updates and requests for feedback on Linuxmusicians), but I really (really) can't figure out how to test this.
- I've never used Github Actions before, and when I open the Actions tab all I can see is a whopping 3444 workflow runs in more or less successful states. If I try my luck and click on a latest successful run of something that looks like a Linux build, I still can't find any assets to download :shrug: 
- Then on the announcement board you suggest to alternatively install it using pip, but I can't find anything like shoopdaloop using pip commands or on PyPi.
- The installation from source seems to be pretty well documented, but I haven't managed yet (`No module named 'py_build_cmake'`, maybe I missed a dependency, but then when I install `py_build_cmake` via `pip` I get an error about cpython's abi version - I'll try again later)

If you really want early feedback on your program, I would really advise you to expand a bit more on explanations to install and run it. I am by no means an expert but I'm not a beginner either, so I think it would be good enough to have non-straightforward yet step-by-step instructions to build from source, and after that pre-built packages can wait a few more months ; otherwise I'm afraid that many enthusiasts like me will give up before having been able to test anything.
I find this even more frustrating especially because you seem to pay a lot of attention to the documentation, which looks otherwise great!

Hope this helps.

**Comment by SanderVocke** [comment]
Hi @zigmhount,

Thanks for posting your thoughts. Looks like I underestimated how hard it is to find the correct artifacts to download. I didn't mean to obscure them, but until now I just didn't want to post them to the "releases" page because if it looks like a release, the expectation might be a finished & polished product (which at the moment it isn't yet).

But point taken. I think I will just make a "rolling pre-release" page where I post all the latest artifacts for download, with a disclaimer that it's a development version. I'll do so and post a link here when I'm done.

**Comment by SanderVocke** [comment]
I created the pre-release page [here](https://github.com/SanderVocke/shoopdaloop/releases/tag/dev-prerelease).

Please bear with me - you are one of the first to run it, and the first to report back. Let me know if you have further issues!

**Comment by zigmhount** [comment]
Awesome, thank you so much!
I've tried the portable version and read through the documentation, and it all looks very good. I've been myself trying all the open-source looping solutions I could find (I'm usually recording and looping MIDI) and dreaming of the ultimate one - and started implementing a couple of ideas on my own (mostly in Pure Data and in Python), but I'm not much of a programmer so my current project is more realistically focused on interfacing my APCmini with Seq192. But Shoopdaloop is pretty much doing all I was thinking of, while maintaining a lot of flexibility, great job!
I'll be playing around and reporting back, probably starting by reviewing the open bugs and chipping in if I can. Let me know if there's anything specific I could help with.

**Comment by SanderVocke** [comment]
Great, I appreciate the feedback! I saw you already posted a few comments and ideas, that's wonderful.

For me, I formed this idea of what I imagined jamming solo should be like with a looping program and multiple physical instruments and synthesis/FX plugins, and that's how this project started. The only other way I could see it happening would be by switching my preferred environment to Windows/Mac, investing in Ableton and then installing third-party plugins which achieve some of this advanced looping functionality, but probably not in a very user-friendly way.

At the moment I am finding that instead of making music, which was the point, I am mostly working on this project instead. Ah well, at some point the balance will shift, and meanwhile working on this is also fun. Seeing some outside interest is definitely motivating.

I think it's pretty cool that apparently, what I am envisioning matches to some degree with what you were looking for, even though it will definitely take time to come to fruition.

I can't think of anything specific to ask you for off the top of my head. Mostly I am wondering if there are any major gaps in terms of features (including to-do features already listed in the issue list), that would make this a dealbreaker. Also curious for the ideas you had for your own project - who knows, that might be inspiring.

One thing though, we are discussing here on another topic and getting a bit off-topic. For this kind of general conversation, could you create a post in the Discussion board section instead?

**Comment by SanderVocke** [comment]
Come to think of it, I do have a specific question: would like to know what went wrong with your source build. I am surprised you had to install `py_build_cmake` manually - the python build should pull in and install the dependencies, including this one, automatically.

**Comment by SanderVocke** [comment]
In the meantime, I'm going to close this issue again as I think the original question was addressed. I will still check back here to see replies!

**Comment by zigmhount** [comment]
All right, started a discussion topic in https://github.com/SanderVocke/shoopdaloop/discussions/301 :)

> I am surprised you had to install py_build_cmake manually - the python build should pull in and install the dependencies, including this one, automatically.
Do you have any more info on what command you ran, your environment etc? Could you post it as a separate issue ticket?

As far as I recall, I basically installed the packages listed from `sh distribution/dependencies/get_dependencies.sh distribution/dependencies/build_base_debian` and `sh distribution/dependencies/get_dependencies.sh distribution/dependencies/run_base_debian`, created a venv with `python3 -m venv venv` and ran `python3 -m build --no-isolation --wheel .`. At no point did it seem to attempt install additional python packages by itself, so I probably missed a step... I'll try again and create another ticket.

Python 3.11.2 on MX Linux (Debian-based)
